# Generated by Django 3.2.24 on 2024-02-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='password',
            field=models.IntegerField(default=1234, max_length=10),
        ),
    ]
