# Generated by Django 3.2.24 on 2024-02-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_blog_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('userid', models.CharField(max_length=20, verbose_name='유저ID')),
                ('nickname', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='닉네임')),
                ('email', models.EmailField(max_length=100, verbose_name='유저메일')),
                ('password', models.CharField(max_length=20, verbose_name='유저PW')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='가입일')),
            ],
            options={
                'verbose_name': '게시판 멤버',
                'verbose_name_plural': '게시판 멤버',
                'db_table': 'boardmembers',
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='password',
            field=models.IntegerField(default=1234),
        ),
    ]
