# Generated by Django 3.2.24 on 2024-02-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20240219_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='가입일'),
        ),
    ]
