# Generated by Django 3.2.24 on 2024-02-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_alter_boardmember_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
